package midi

object MidiControlNumbers extends Enumeration {
  type CCNum = Value
  val BANK_SELECT = Value(0)
  val MODULATION_WHEEL_OR_LEVER = Value(1)
  val BREATH_CONTROLLER = Value(2)
  val UNDEFINED = Value(3)
  val FOOT_CONTROLLER = Value(4)
  val PORTAMENTO_TIME = Value(5)
  val DATA_ENTRY_MSB = Value(6)
  val CHANNEL_VOLUME = Value(7)
  val BALANCE = Value(8)
  val PAN = Value(10)
  val EXPRESSION_CONTROLLER = Value(11)
  val EFFECT_CONTROL_1 = Value(12)
  val EFFECT_CONTROL_2 = Value(13)
  val GENERAL_PURPOSE_CONTROLLER_1 = Value(16)
  val GENERAL_PURPOSE_CONTROLLER_2 = Value(17)
  val GENERAL_PURPOSE_CONTROLLER_3 = Value(18)
  val GENERAL_PURPOSE_CONTROLLER_4 = Value(19)
  val DAMPER_PEDAL = Value(64)
  val PORTAMENTO = Value(65)
  val SOSTENUTO = Value(66)
  val SOFT_PEDAL = Value(67)
  val LEGATO_FOOTSWITCH = Value(68)
  val HOLD_2 = Value(69)
  val SOUND_VARIATION = Value(70)
  val TIMBRE_HARMONIC_INTENS = Value(71)
  val RELEASE_TIME = Value(72)
  val ATTACK_TIME = Value(73)
  val BRIGHTNESS = Value(74)
  val DECAY_TIME = Value(75)
  val VIBRATO_RATE = Value(76)
  val VIBRATO_DEPTH = Value(77)
  val VIBRATO_DELAY = Value(78)
  val GENERAL_PURPOSE_CONTROLLER_5 = Value(80)
  val GENERAL_PURPOSE_CONTROLLER_6 = Value(81)
  val GENERAL_PURPOSE_CONTROLLER_7 = Value(82)
  val GENERAL_PURPOSE_CONTROLLER_8 = Value(83)
  val PORTAMENTO_CONTROL = Value(84)
  val HIGH_RESOLUTION_VELOCITY_PREFIX = Value(88)
  val EFFECTS_1_DEPTH = Value(91)
  val EFFECTS_2_DEPTH = Value(92)
  val EFFECTS_3_DEPTH = Value(93)
  val EFFECTS_4_DEPTH = Value(94)
  val EFFECTS_5_DEPTH = Value(95)

  val FILTER_CUTOFF = Value(20)
  val FILTER_RESONANCE = Value(21)
  val FILTER_LOW_PASS = Value(22)
  val FILTER_BAND_PASS = Value(23)
  val FILTER_HIGH_PASS = Value(24)

  val KICK_ATTACK = Value(25)
  val KICK_DECAY = Value(26)
  val KICK_SUSTAIN = Value(27)
  val KICK_RELEASE = Value(28)

  val SNARE_ATTACK = Value(29)
  val SNARE_DECAY = Value(30)
  val SNARE_SUSTAIN = Value(31)
  val SNARE_RELEASE = Value(32)

  val HHO_ATTACK = Value(33)
  val HHO_DECAY = Value(34)
  val HHO_SUSTAIN = Value(35)
  val HHO_RELEASE = Value(36)

  val HHC_ATTACK = Value(37)
  val HHC_DECAY = Value(38)
  val HHC_SUSTAIN = Value(39)
  val HHC_RELEASE = Value(40)

  val HHP_ATTACK = Value(41)
  val HHP_DECAY = Value(42)
  val HHP_SUSTAIN = Value(43)
  val HHP_RELEASE = Value(44)
}
